import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./context/userContext";
import { CaptainProvider } from "./context/captainContext";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ubar",
  description: "Generated by waliul hasan",
};

export default function RootLayout({ children }) {
  
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <UserProvider>
          <CaptainProvider>
            <Navbar />
            {children}
            <Footer />
          </CaptainProvider>
        </UserProvider>
      </body>
    </html>
  );
}
